[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[plugins]]
  package = "@netlify/plugin-react"

  [[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"